nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@remix-run/dev@*':
    dependencies:
      '@remix-run/node': '*'
      'remix': '*'
      '@remix-run/server-runtime': '*'
      '@remix-run/react': '*'
